services:
  web:
    container_name: djangoweb
    build: .
    command: /djangoweb/scripts/entrypoint.sh
    ports:
      - "80:8000"
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A core worker -B --loglevel=info && celery -A core beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web