# Generated by Django 5.2 on 2025-06-05 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cavalo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do leilão', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do leilão', null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('finalizado', 'Finalizado')], default='ativo', max_length=20)),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leiloes', to='cavalo.cavalo')),
            ],
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='cavalo.cavalo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='leilao.leilao')),
            ],
        ),
    ]
