# Generated by Django 5.2 on 2025-06-05 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0001_initial'),
        ('leilao', '0002_alter_lance_cavalo_alter_lance_leilao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='cavalo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lance_cavalo', to='cavalo.cavalo'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='cavalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leilao_cavalo', to='cavalo.cavalo'),
        ),
    ]
