# Generated by Django 5.2 on 2025-07-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0003_alter_lance_cavalo_alter_leilao_cavalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='data_leilao',
            field=models.DateTimeField(blank=True, help_text='Data e hora do leilão', null=True),
        ),
    ]
