# Generated by Django 5.2 on 2025-07-02 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0008_alter_cavalo_leilao'),
        ('leilao', '0004_leilao_data_leilao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='cavalo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cavalo_leilao', to='cavalo.cavalo'),
        ),
    ]
