# Generated by Django 5.2 on 2025-07-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0005_alter_leilao_cavalo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leilao',
            name='cavalo',
        ),
    ]
