# Generated by Django 5.2 on 2025-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0006_remove_leilao_cavalo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='imagem',
            field=models.ImageField(default='leiloes/default.jpg', upload_to='leilao/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leilao',
            name='termos',
            field=models.TextField(blank=True, help_text='Termos do leilão', null=True),
        ),
    ]
