# Generated by Django 5.2 on 2025-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0007_leilao_imagem_leilao_termos'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
    ]
