# Generated by Django 5.2 on 2025-07-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0008_leilao_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
