# Generated by Django 5.2 on 2025-07-23 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0009_alter_leilao_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='termos',
            field=models.FileField(blank=True, help_text='Arquivo PDF com os termos do leilão', null=True, upload_to='leilao/termos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Termos do Leilão (PDF)'),
        ),
    ]
