# Generated by Django 5.2 on 2025-06-05 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cavalo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('descricao', models.TextField()),
                ('informacoes', models.TextField(blank=True, null=True)),
                ('registro', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Registro deve conter apenas letras maiúsculas, números e hífens')])),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('nascimento', models.DateField(blank=True, help_text='Data de nascimento do cavalo', null=True)),
                ('geracao', models.CharField(blank=True, help_text='Geração do cavalo', max_length=50, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura em metros', max_digits=3, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=10)),
                ('pelagem', models.CharField(blank=True, help_text='Tipo de pelagem', max_length=30, null=True)),
                ('alojamento', models.CharField(blank=True, help_text='Local de alojamento do cavalo', max_length=100, null=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='disponivel', help_text='Status do cavalo', max_length=20)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, help_text='Preço do cavalo', max_digits=10, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data de cadastro do cavalo')),
                ('avo_materna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avo_materna_2', to='cavalo.cavalo')),
                ('avo_materno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avo_materno_1', to='cavalo.cavalo')),
                ('avo_paterna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avo_paterna_2', to='cavalo.cavalo')),
                ('avo_paterno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avo_paterno_1', to='cavalo.cavalo')),
                ('bisavo_materna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bisavo_materno_2', to='cavalo.cavalo')),
                ('bisavo_materno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bisavo_materno_1', to='cavalo.cavalo')),
                ('bisavo_paterna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bisavo_paterno_2', to='cavalo.cavalo')),
                ('bisavo_paterno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bisavo_paterno_1', to='cavalo.cavalo')),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cavalos_criador', to=settings.AUTH_USER_MODEL)),
                ('mae', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_mae', to='cavalo.cavalo')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos_pai', to='cavalo.cavalo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cavalos_vendedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos_cavalos/')),
                ('legenda', models.CharField(blank=True, max_length=200)),
                ('destaque', models.BooleanField(default=False, help_text='Marque como destaque para exibir na página principal')),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='cavalo.cavalo')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_youtube', models.URLField()),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('cavalo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='cavalo.cavalo')),
            ],
        ),
    ]
