# Generated by Django 5.2 on 2025-07-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0001_initial'),
        ('leilao', '0003_alter_lance_cavalo_alter_leilao_cavalo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cavalo',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='cavalo',
            name='leilao',
            field=models.ForeignKey(blank=True, help_text='Leilão ao qual o cavalo está vinculado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalos', to='leilao.leilao'),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='parcelas',
            field=models.IntegerField(blank=True, help_text='Número de parcelas', null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço Inicial da parcela', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='raca',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
