# Generated by Django 5.2 on 2025-07-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0002_remove_cavalo_data_nascimento_cavalo_leilao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cavalo',
            name='preco',
        ),
        migrations.AddField(
            model_name='cavalo',
            name='lance_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lance Inicial da parcela', max_digits=10, null=True),
        ),
    ]
