# Generated by Django 5.2 on 2025-07-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0003_remove_cavalo_preco_cavalo_lance_inicial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cavalo',
            old_name='parcelas',
            new_name='parcela',
        ),
    ]
