# Generated by Django 5.2 on 2025-07-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0005_alter_cavalo_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='avo_materna',
            field=models.CharField(blank=True, help_text='Avó Materna', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='avo_materno',
            field=models.CharField(blank=True, help_text='Avô Materno', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='avo_paterna',
            field=models.CharField(blank=True, help_text='Avó Paterna', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='avo_paterno',
            field=models.CharField(blank=True, help_text='Avô Paterno', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='bisavo_materna',
            field=models.CharField(blank=True, help_text='Bisavó Materna', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='bisavo_materno',
            field=models.CharField(blank=True, help_text='Bisavô Materno', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='bisavo_paterna',
            field=models.CharField(blank=True, help_text='Bisavó Paterna', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='bisavo_paterno',
            field=models.CharField(blank=True, help_text='Bisavô Paterno', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='mae',
            field=models.CharField(blank=True, help_text='Mãe do cavalo', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='pai',
            field=models.CharField(blank=True, help_text='Pai do cavalo', max_length=30, null=True),
        ),
    ]
