# Generated by Django 5.2 on 2025-07-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0006_alter_cavalo_avo_materna_alter_cavalo_avo_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='criador',
            field=models.CharField(blank=True, help_text='Criador do cavalo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='vendedor',
            field=models.CharField(blank=True, help_text='Vendedor do cavalo', max_length=100, null=True),
        ),
    ]
