# Generated by Django 5.2 on 2025-07-02 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0007_alter_cavalo_criador_alter_cavalo_vendedor'),
        ('leilao', '0004_leilao_data_leilao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='leilao',
            field=models.ForeignKey(blank=True, help_text='Leilão ao qual o cavalo está vinculado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leilao_cavalo', to='leilao.leilao'),
        ),
    ]
