# Generated by Django 5.2 on 2025-07-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0008_alter_cavalo_leilao'),
        ('leilao', '0006_remove_leilao_cavalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='leilao',
            field=models.ForeignKey(blank=True, help_text='Leilão ao qual o cavalo está vinculado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cavalos_leilao', to='leilao.leilao'),
        ),
    ]
