# Generated by Django 5.2 on 2025-07-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0009_alter_cavalo_leilao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='titulo',
            new_name='legenda',
        ),
    ]
