# Generated by Django 5.2 on 2025-07-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0010_rename_titulo_video_legenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('C', 'Castrado')], max_length=10),
        ),
    ]
