# Generated by Django 5.2 on 2025-07-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0011_alter_cavalo_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='destaque',
        ),
        migrations.AddField(
            model_name='foto',
            name='is_destaque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foto',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
