# Generated by Django 5.2 on 2025-07-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0012_remove_foto_destaque_foto_is_destaque_foto_ordem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='legenda',
        ),
    ]
