# Generated by Django 5.2 on 2025-07-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0013_remove_foto_legenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(blank=True, default='leiloes/default.jpg', null=True, upload_to='leiloes/'),
        ),
    ]
