# Generated by Django 5.2 on 2025-07-13 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0015_cavalo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='registro',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z0-9-]+$', 'Registro deve conter apenas letras maiúsculas, números e hífens')]),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagem',
            field=models.ImageField(blank=True, default='leiloes/default.jpg', null=True, upload_to='fotos_cavalos/'),
        ),
    ]
