# Generated by Django 5.2 on 2025-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0016_alter_cavalo_registro_alter_cavalo_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cavalo',
            old_name='bisavo_materno',
            new_name='bisavo_materno1',
        ),
        migrations.RenameField(
            model_name='cavalo',
            old_name='bisavo_paterno',
            new_name='bisavo_paterno1',
        ),
        migrations.RemoveField(
            model_name='cavalo',
            name='bisavo_materna',
        ),
        migrations.RemoveField(
            model_name='cavalo',
            name='bisavo_paterna',
        ),
        migrations.AddField(
            model_name='cavalo',
            name='bisavo_materno2',
            field=models.CharField(blank=True, help_text='Bisavó Materno', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='bisavo_materno3',
            field=models.CharField(blank=True, help_text='Bisavô Materno', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='bisavo_materno4',
            field=models.CharField(blank=True, help_text='Bisavó Materno', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='bisavo_paterno2',
            field=models.CharField(blank=True, help_text='Bisavó Paterno', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='bisavo_paterno3',
            field=models.CharField(blank=True, help_text='Bisavô Paterno', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cavalo',
            name='bisavo_paterno4',
            field=models.CharField(blank=True, help_text='Bisavó Paterno', max_length=30, null=True),
        ),
    ]
