# Generated by Django 5.2 on 2025-07-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0017_rename_bisavo_materno_cavalo_bisavo_materno1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cavalo',
            name='informacoes',
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='registro',
            field=models.CharField(max_length=50),
        ),
    ]
