# Generated by Django 5.2 on 2025-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0018_remove_cavalo_informacoes_alter_cavalo_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavalo',
            name='incremento_lance',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Valor mínimo de incremento entre lances', max_digits=10),
        ),
    ]
