# Generated by Django 5.2 on 2025-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0019_cavalo_incremento_lance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='incremento_lance',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Valor mínimo de incremento entre lances', max_digits=10),
        ),
    ]
