# Generated by Django 5.2 on 2025-07-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0020_alter_cavalo_incremento_lance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cavalo',
            name='lote',
            field=models.IntegerField(blank=True, help_text='Número do lote no leilão', null=True),
        ),
        migrations.AlterField(
            model_name='cavalo',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea'), ('C', 'Castrado')], max_length=10, null=True),
        ),
    ]
