# Generated by Django 5.2 on 2025-07-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0021_cavalo_lote_alter_cavalo_sexo'),
        ('leilao', '0010_alter_leilao_termos'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cavalo',
            unique_together={('leilao', 'lote')},
        ),
    ]
