# Generated by Django 5.2 on 2025-09-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0022_alter_cavalo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='incremento_lance',
            field=models.DecimalField(blank=True, decimal_places=2, default=50.0, help_text='Valor mínimo de incremento entre lances', max_digits=10, null=True),
        ),
    ]
