# Generated by Django 5.2 on 2025-10-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cavalo', '0023_alter_cavalo_incremento_lance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cavalo',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Macho'), ('F', 'Fêmea'), ('C', 'Castrado'), ('G', 'Garanhão')], max_length=10, null=True),
        ),
    ]
