# Generated by Django 5.2 on 2025-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=models.CharField(blank=True, max_length=300, verbose_name='Resumo'),
        ),
    ]
