# Generated by Django 5.2 on 2025-10-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_resumo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Opinião', 'verbose_name_plural': 'Opiniões'},
        ),
    ]
