# Generated by Django 5.2 on 2025-06-05 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(help_text='Pessoa Física - Formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato 000.000.000-00')])),
                ('cnpj', models.CharField(help_text='Pessoa Jurídica - Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ deve estar no formato 00.000.000/0000-00')])),
                ('rg_ie', models.CharField(max_length=15)),
                ('emis_uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Selecione o estado', max_length=2)),
                ('nasc_fund', models.DateField()),
                ('profis_cnae', models.CharField(max_length=25)),
                ('representante', models.CharField(blank=True, help_text='Nome do representante legal, se aplicável', max_length=200)),
                ('cpf_repres', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato 000.000.000-00')])),
                ('end_rua_av', models.CharField(max_length=200)),
                ('end_numero', models.CharField(max_length=10)),
                ('end_complem', models.CharField(blank=True, max_length=100)),
                ('end_bairro', models.CharField(max_length=100)),
                ('end_cidade', models.CharField(max_length=100)),
                ('end_estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Selecione o estado', max_length=2)),
                ('end_cep', models.CharField(help_text='Formato: 00000-000', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP deve estar no formato 00000-000')])),
                ('telefone', models.CharField(blank=True, help_text='Formato: (11) 1234-5678', max_length=15, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}\\d{10,14}$', 'Telefone deve estar no formato (11) 1234-5678')])),
                ('celular', models.CharField(help_text='Formato: (11) 91234-5678', max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\) 9\\d{4}-\\d{4}$', 'Celular deve estar no formato (11) 91234-5678')])),
                ('email', models.EmailField(help_text='Email deve ser único', max_length=254, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [],
            },
        ),
    ]
