# Generated by Django 5.2 on 2025-07-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilcliente',
            options={},
        ),
    ]
