# Generated by Django 5.2 on 2025-07-14 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_perfilcliente_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='celular',
            field=models.CharField(help_text='Formato: (11) 91234-5678', max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\) 9\\d{4}-\\d{4}$', 'Celular deve estar no formato (11) 91234-5678')], verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='cnpj',
            field=models.CharField(help_text='Pessoa Jurídica - Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ deve estar no formato 00.000.000/0000-00')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='cpf',
            field=models.CharField(help_text='Pessoa Física - Formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato 000.000.000-00')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='cpf_repres',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato 000.000.000-00')], verbose_name='CPF do Representante'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='email',
            field=models.EmailField(help_text='Email deve ser único', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='emis_uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Selecione o estado', max_length=2, verbose_name='UF de Emissão'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='end_bairro',
            field=models.CharField(max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='end_cep',
            field=models.CharField(help_text='Formato: 00000-000', max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP deve estar no formato 00000-000')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='end_cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='end_complem',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='end_estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Selecione o estado', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='end_numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='end_rua_av',
            field=models.CharField(max_length=200, verbose_name='Rua/Avenida'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='nasc_fund',
            field=models.DateField(help_text='Formato: DD/MM/AAAA', verbose_name='Data de Nascimento/Fundação'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='profis_cnae',
            field=models.CharField(help_text='Código CNAE ou profissão', max_length=25, verbose_name='Profissão/CNAE'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='representante',
            field=models.CharField(blank=True, help_text='Nome do representante legal, se aplicável', max_length=200, verbose_name='Nome do Representante'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='rg_ie',
            field=models.CharField(max_length=15, verbose_name='RG/IE'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (11) 1234-5678', max_length=15, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}\\d{10,14}$', 'Telefone deve estar no formato (11) 1234-5678')], verbose_name='Telefone'),
        ),
    ]
