# Generated by Django 5.2 on 2025-07-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_perfilcliente_celular_alter_perfilcliente_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcliente',
            name='email',
        ),
    ]
