# Generated by Django 5.2 on 2025-07-14 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_perfilcliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Pessoa Jurídica - Formato: 00.000.000/0000-00', max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ deve estar no formato 00.000.000/0000-00')], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='cpf_repres',
            field=models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF deve estar no formato 000.000.000-00')], verbose_name='CPF do Representante'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='end_complem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='profis_cnae',
            field=models.CharField(blank=True, help_text='Código CNAE ou profissão', max_length=25, null=True, verbose_name='Profissão/CNAE'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='representante',
            field=models.CharField(blank=True, help_text='Nome do representante legal, se aplicável', max_length=200, null=True, verbose_name='Nome do Representante'),
        ),
    ]
