# Generated by Django 5.2 on 2025-07-14 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_perfilcliente_cnpj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='telefone',
            field=models.CharField(blank=True, help_text='Formato: (11) 1234-5678', max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+\\d{1,3}\\d{10,14}$', 'Telefone deve estar no formato (11) 1234-5678')], verbose_name='Telefone'),
        ),
    ]
