# Generated by Django 5.2 on 2025-07-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_perfilcliente_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilcliente',
            name='cpf_repres',
        ),
        migrations.RemoveField(
            model_name='perfilcliente',
            name='representante',
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='propr_cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade da Propriedade'),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='propr_estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Selecione o estado', max_length=2, null=True, verbose_name='Estado da Propriedade'),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='propriedade',
            field=models.CharField(blank=True, help_text='Nome do Propriedade, se aplicável', max_length=200, null=True, verbose_name='Nome da Propriedade'),
        ),
    ]
