# Generated by Django 5.2 on 2025-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_perfilcliente_cpf_repres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='nome_completo',
            field=models.CharField(default='usuario', help_text='Nome completo do cliente', max_length=100, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
    ]
