# Generated by Django 5.2 on 2025-07-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_perfilcliente_nome_completo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfilcliente',
            options={'verbose_name': 'Perfil do Cliente', 'verbose_name_plural': 'Perfis dos Clientes'},
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='status',
            field=models.CharField(choices=[('analise', 'Em Análise'), ('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso')], default='analise', help_text='Status atual do cliente no sistema', max_length=10, verbose_name='Status'),
        ),
    ]
