# Generated by Django 5.2 on 2025-11-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_perfilcliente_options_perfilcliente_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='status',
            field=models.CharField(choices=[('analise', 'Em Análise'), ('ativo', 'Aprovado'), ('inativo', 'Recusado'), ('suspenso', 'Suspenso')], default='analise', help_text='Status atual do cliente no sistema', max_length=10, verbose_name='Status'),
        ),
    ]
